# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComputerVision' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComputerVision
  pod 'OpenCV'

  target 'ComputerVisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComputerVisionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
